// v1.3.1 i18n patch — adds preset-bridge diagnostic strings to data_i18n.js
// (id + en). Idempotent: existing keys are never overwritten.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const FILE = '/home/z/my-project/build/LittleDevilCompanionTT/data_i18n.js';

const ADD = {
    id: {
        'ui.menu.status': 'Status integrasi',
        'ui.menu.saveNow': 'Simpan sekarang',
        'ui.menu.syncTest': 'Uji sinkronisasi',
        'ui.menu.title': 'Menu',
        'runtime.toast.saveNow': 'Tersimpan ke chat',
        'runtime.toast.syncOk': 'Sinkron OK — {n}/{total} variabel preset aktif di chat ini',
        'runtime.toast.syncFail': 'Sinkron GAGAL — muat ulang chat lalu coba lagi',
        'runtime.sync.stptOn': 'ST-Prompt-Template aktif',
        'runtime.sync.stptOff': 'ST-Prompt-Template tidak terdeteksi',
        'runtime.sync.stptDisabled': 'ST-Prompt-Template dipatikan di pengaturannya',
        'runtime.sync.stptGenOff': 'Pemrosesan generate ST-Prompt-Template dimatikan',
        'runtime.sync.seeded': 'variabel ter-seed',
        'runtime.sync.banner': 'Preset butuh ST-Prompt-Template — variabel dashboard tidak terbaca AI',
        'runtime.sync.hint': 'Install/aktifkan via Extensions → Install extension → github.com/zonde306/ST-Prompt-Template',
    },
    en: {
        'ui.menu.status': 'Integration status',
        'ui.menu.saveNow': 'Save now',
        'ui.menu.syncTest': 'Sync self-test',
        'ui.menu.title': 'Menu',
        'runtime.toast.saveNow': 'Saved to chat',
        'runtime.toast.syncOk': 'Sync OK — {n}/{total} preset variables active in this chat',
        'runtime.toast.syncFail': 'Sync FAILED — reload the chat and try again',
        'runtime.sync.stptOn': 'ST-Prompt-Template active',
        'runtime.sync.stptOff': 'ST-Prompt-Template not detected',
        'runtime.sync.stptDisabled': 'ST-Prompt-Template is disabled in its settings',
        'runtime.sync.stptGenOff': 'ST-Prompt-Template generate processing is off',
        'runtime.sync.seeded': 'variables seeded',
        'runtime.sync.banner': 'Preset requires ST-Prompt-Template — the AI cannot read dashboard variables',
        'runtime.sync.hint': 'Install/enable via Extensions → Install extension → github.com/zonde306/ST-Prompt-Template',
    },
};

const mod = await import(pathToFileURL(FILE).href);
const L10N = mod.L10N;
if (!L10N || !L10N.id || !L10N.en) throw new Error('L10N shape unexpected');

let added = 0;
for (const [lang, kv] of Object.entries(ADD)) {
    for (const [k, v] of Object.entries(kv)) {
        if (L10N[lang][k] === undefined) { L10N[lang][k] = v; added++; }
    }
}

// Rebuild the module preserving the 2-line header comment.
const header = [
    '// AUTO-GENERATED by scripts/gen_data.js — do not hand-edit.',
    '// Source: little-devil-companion-1.2.0.tpg (entry.js + ui/floating-dashboard.html + locales)',
    '// v1.3.1 additions applied by scripts/patch_i18n_131.mjs (preset-bridge diagnostics).',
].join('\n');
const out = header + '\nexport const L10N = ' + JSON.stringify(L10N) + ';\n';
writeFileSync(FILE, out, 'utf8');
console.log(`i18n patched: ${added} keys added`);
